POST http://localhost:10000/user::1
Content-Type: application/json

{
  "email": "ebkaveca@mail.ru",
  "username": "content",
  "password": "aaaaaaa"
}


### GET request with parameter
GET http://localhost:10000/users
Accept: application/json